### ISSUE TITLE
JACK connections

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [magnetophon/nixosConfig#2]
I've copied much of your code from the top-level `.nix` files in this repo for an experimental [audio branch](https://github.com/JeffreyBenjaminBrown/nixos-experiments/tree/audio) of my own NixOS config.

Does JACK start for you automatically? Can you use sound in the browser and in your JACK-connected apps at the same time, or do you have to reconfigure something when going between those two worlds? Is your setup entirely declarative, or is there some procedural magic I'm missing?

I am able to use sound in the browser normally -- which surprised me, because after emulating your code, mine contains no mention of pulseaudio. However, no matter what I do, Cadence tells me that "jackdbus is not available". When I use SuperCollider it looks like it's working but I hear nothing.

I described in detail [on the NixOS.org Discourse forum](https://discourse.nixos.org/t/declarative-audio-config-how-to-start-and-maybe-use-jack/5458) the changes I made to align my config with yours. I would have mentioned you but I couldn't find your username on that forum, if you've got one.

**Comment by JeffreyBenjaminBrown** [comment]
Update: I think I found a problem in musnix -- it's using a version of rtirq no longer hosted by the mirrors NixOS uses (although a newer one is). Until that's resolved I can't build the realtime kernel, or enable the `musnix.rtirq` options it makes possible. Therefore I haven't yet emulated some of your config.

**Comment by magnetophon** [comment]
> Can you use sound in the browser and in your JACK-connected apps at the same time?
No, I just start jack when I need it, and stop it when I want browser audio.

My setup is entirely declarative. It's the reop you found together with my dotfiles repo.
I don't think you need anyting from there though.

You don't need pulseaudio for browser sound, you can also just use plain alsa, which is what I do.

Good luck, and keep me posted, maybe best in the nix pro audio issue, cause that's where I gave some tips.

**Comment by JeffreyBenjaminBrown** [comment]
For the benefit of future hypothetical readers:

Eschewing the declarative JACK service and starting it manually via Qjackctl worked!

> keep me posted, maybe best in the nix pro audio issue

Here's [that pro audio issue](https://github.com/NixOS/nixpkgs/issues/71283).
