### ISSUE TITLE
Why the older kernel?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [magnetophon/nixosConfig#3]
Under `musnix` in your [commonRT](https://github.com/magnetophon/nixosConfig/blob/master/commonRT.nix) file, you include the line
```
  kernel.packages = pkgs.linuxPackages_4_19_rt;
```

The Musnix default is a newer one, `5_0_rt`. Why do you (and more to the point, should I) prefer `4_19_rt`?

**Comment by magnetophon** [comment]
At the moment the musnix rt kernel is broken, and I managed to fix it in a hacky way, that only works for one kernel at a time. I chose to "fix" the one that unstable non-rt is using.
You don't need any rt kernel, unless you need super-reliable low-latency audio.
Unlikely to be needed when you wanna do audio programming, but you be the judge of that!
